version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    restart: on-failure
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - "ES_VERSION=8.2.2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - nckh

  kibana:
    image: 'docker.elastic.co/kibana/kibana:8.2.2'
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    networks:
      - nckh
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  database:
    build:
      context: .
      dockerfile: PostgresDockerfile
    container_name: database
    ports:
      - '5432:5432'
    networks:
      - nckh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - nckh

  pgsync:
    build:
      context: .
      dockerfile: PgsyncDockerfile
    container_name: pgsync
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=postgres
      - PG_HOST=database
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_HOST=redis
    networks:
      - nckh
networks:
  nckh:
    external: true